# Generated by Django 3.1.4 on 2020-12-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='categories',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
