# Generated by Django 3.1.4 on 2020-12-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201221_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to=''),
        ),
    ]
